//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrmProgress
    {
        public int Id { get; set; }
        public Nullable<int> DrmId { get; set; }
        public Nullable<int> DeliveryProgressId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> Confirmed { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
    
        public virtual DispatchRequisitionMonitoring DispatchRequisitionMonitoring { get; set; }
    }
}
