//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WLTIDeliveryToolsEntities1 : DbContext
    {
        public WLTIDeliveryToolsEntities1()
            : base("name=WLTIDeliveryToolsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ChannelSalesExecutive> ChannelSalesExecutives { get; set; }
        public virtual DbSet<DeliveryStatus> DeliveryStatus1 { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DrmProgress> DrmProgresses { get; set; }
        public virtual DbSet<DeliveryProgress> DeliveryProgresses { get; set; }
        public virtual DbSet<DeliveryOption> DeliveryOptions { get; set; }
        public virtual DbSet<EstimatedDelivery> EstimatedDeliveries { get; set; }
        public virtual DbSet<ModeOfDelivery> ModeOfDeliveries { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<DispatchRequisitionMonitoring> DispatchRequisitionMonitorings { get; set; }
    }
}
